print("Hello World")
print("I am learning git. pranav")
print("I am learning git. pranav")
print("I am learning git. pranav")
print("I am learning git. ajinkya")
print("I am learning git. ajinkya")
print("I am learning git. ajinkya")
print("I am learning git. ajinkya pranav")
